hparams: !!python/object:argparse.Namespace
  batch_size: 2
  ckpt_path: null
  config: configs/v1/kitti_raw.txt
  dataset_dir: F:\kitti
  dataset_name: kitti
  epoch_size: 1000
  exp_name: kitti_sc-depth_v1
  geometry_weight: 0.1
  input_dir: null
  lr: 0.0001
  model_version: v1
  no_auto_mask: false
  no_dynamic_mask: false
  no_min_optimize: false
  no_ssim: false
  num_epochs: 100
  output_dir: null
  photo_weight: 1.0
  resnet_layers: 18
  rot_c_weight: 1.0
  rot_t_weight: 1.0
  save_depth: false
  save_vis: false
  sequence_length: 3
  skip_frames: 1
  smooth_weight: 0.1
  use_frame_index: false
  val_mode: depth
